// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package db;

public final class DatabaseProtos {
  private DatabaseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MovieOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Movie)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 movieId = 1;</code>
     */
    boolean hasMovieId();
    /**
     * <code>required int32 movieId = 1;</code>
     */
    int getMovieId();

    /**
     * <code>required string title = 2;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>required string genres = 3;</code>
     */
    boolean hasGenres();
    /**
     * <code>required string genres = 3;</code>
     */
    java.lang.String getGenres();
    /**
     * <code>required string genres = 3;</code>
     */
    com.google.protobuf.ByteString
        getGenresBytes();
  }
  /**
   * Protobuf type {@code protobuf.Movie}
   */
  public  static final class Movie extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Movie)
      MovieOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Movie.newBuilder() to construct.
    private Movie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Movie() {
      title_ = "";
      genres_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Movie(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              movieId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              title_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              genres_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return db.DatabaseProtos.internal_static_protobuf_Movie_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return db.DatabaseProtos.internal_static_protobuf_Movie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              db.DatabaseProtos.Movie.class, db.DatabaseProtos.Movie.Builder.class);
    }

    private int bitField0_;
    public static final int MOVIEID_FIELD_NUMBER = 1;
    private int movieId_;
    /**
     * <code>required int32 movieId = 1;</code>
     */
    public boolean hasMovieId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 movieId = 1;</code>
     */
    public int getMovieId() {
      return movieId_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>required string title = 2;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENRES_FIELD_NUMBER = 3;
    private volatile java.lang.Object genres_;
    /**
     * <code>required string genres = 3;</code>
     */
    public boolean hasGenres() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string genres = 3;</code>
     */
    public java.lang.String getGenres() {
      java.lang.Object ref = genres_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          genres_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string genres = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGenresBytes() {
      java.lang.Object ref = genres_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genres_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMovieId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGenres()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, movieId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, genres_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, movieId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, genres_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof db.DatabaseProtos.Movie)) {
        return super.equals(obj);
      }
      db.DatabaseProtos.Movie other = (db.DatabaseProtos.Movie) obj;

      if (hasMovieId() != other.hasMovieId()) return false;
      if (hasMovieId()) {
        if (getMovieId()
            != other.getMovieId()) return false;
      }
      if (hasTitle() != other.hasTitle()) return false;
      if (hasTitle()) {
        if (!getTitle()
            .equals(other.getTitle())) return false;
      }
      if (hasGenres() != other.hasGenres()) return false;
      if (hasGenres()) {
        if (!getGenres()
            .equals(other.getGenres())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMovieId()) {
        hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
        hash = (53 * hash) + getMovieId();
      }
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasGenres()) {
        hash = (37 * hash) + GENRES_FIELD_NUMBER;
        hash = (53 * hash) + getGenres().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static db.DatabaseProtos.Movie parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static db.DatabaseProtos.Movie parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static db.DatabaseProtos.Movie parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static db.DatabaseProtos.Movie parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static db.DatabaseProtos.Movie parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static db.DatabaseProtos.Movie parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static db.DatabaseProtos.Movie parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static db.DatabaseProtos.Movie parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static db.DatabaseProtos.Movie parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static db.DatabaseProtos.Movie parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static db.DatabaseProtos.Movie parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static db.DatabaseProtos.Movie parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(db.DatabaseProtos.Movie prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Movie}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Movie)
        db.DatabaseProtos.MovieOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return db.DatabaseProtos.internal_static_protobuf_Movie_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return db.DatabaseProtos.internal_static_protobuf_Movie_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                db.DatabaseProtos.Movie.class, db.DatabaseProtos.Movie.Builder.class);
      }

      // Construct using db.DatabaseProtos.Movie.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        movieId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        genres_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return db.DatabaseProtos.internal_static_protobuf_Movie_descriptor;
      }

      @java.lang.Override
      public db.DatabaseProtos.Movie getDefaultInstanceForType() {
        return db.DatabaseProtos.Movie.getDefaultInstance();
      }

      @java.lang.Override
      public db.DatabaseProtos.Movie build() {
        db.DatabaseProtos.Movie result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public db.DatabaseProtos.Movie buildPartial() {
        db.DatabaseProtos.Movie result = new db.DatabaseProtos.Movie(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.movieId_ = movieId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.genres_ = genres_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof db.DatabaseProtos.Movie) {
          return mergeFrom((db.DatabaseProtos.Movie)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(db.DatabaseProtos.Movie other) {
        if (other == db.DatabaseProtos.Movie.getDefaultInstance()) return this;
        if (other.hasMovieId()) {
          setMovieId(other.getMovieId());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasGenres()) {
          bitField0_ |= 0x00000004;
          genres_ = other.genres_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMovieId()) {
          return false;
        }
        if (!hasTitle()) {
          return false;
        }
        if (!hasGenres()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        db.DatabaseProtos.Movie parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (db.DatabaseProtos.Movie) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int movieId_ ;
      /**
       * <code>required int32 movieId = 1;</code>
       */
      public boolean hasMovieId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 movieId = 1;</code>
       */
      public int getMovieId() {
        return movieId_;
      }
      /**
       * <code>required int32 movieId = 1;</code>
       */
      public Builder setMovieId(int value) {
        bitField0_ |= 0x00000001;
        movieId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 movieId = 1;</code>
       */
      public Builder clearMovieId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        movieId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object genres_ = "";
      /**
       * <code>required string genres = 3;</code>
       */
      public boolean hasGenres() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string genres = 3;</code>
       */
      public java.lang.String getGenres() {
        java.lang.Object ref = genres_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            genres_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string genres = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGenresBytes() {
        java.lang.Object ref = genres_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          genres_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string genres = 3;</code>
       */
      public Builder setGenres(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        genres_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string genres = 3;</code>
       */
      public Builder clearGenres() {
        bitField0_ = (bitField0_ & ~0x00000004);
        genres_ = getDefaultInstance().getGenres();
        onChanged();
        return this;
      }
      /**
       * <code>required string genres = 3;</code>
       */
      public Builder setGenresBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        genres_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Movie)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Movie)
    private static final db.DatabaseProtos.Movie DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new db.DatabaseProtos.Movie();
    }

    public static db.DatabaseProtos.Movie getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Movie>
        PARSER = new com.google.protobuf.AbstractParser<Movie>() {
      @java.lang.Override
      public Movie parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Movie(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Movie> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Movie> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public db.DatabaseProtos.Movie getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LinkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Link)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 movieId = 1;</code>
     */
    boolean hasMovieId();
    /**
     * <code>required int32 movieId = 1;</code>
     */
    int getMovieId();

    /**
     * <code>required int32 imdbId = 2;</code>
     */
    boolean hasImdbId();
    /**
     * <code>required int32 imdbId = 2;</code>
     */
    int getImdbId();

    /**
     * <code>required int32 tmdbId = 3;</code>
     */
    boolean hasTmdbId();
    /**
     * <code>required int32 tmdbId = 3;</code>
     */
    int getTmdbId();
  }
  /**
   * Protobuf type {@code protobuf.Link}
   */
  public  static final class Link extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Link)
      LinkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Link.newBuilder() to construct.
    private Link(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Link() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Link(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              movieId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              imdbId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              tmdbId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return db.DatabaseProtos.internal_static_protobuf_Link_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return db.DatabaseProtos.internal_static_protobuf_Link_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              db.DatabaseProtos.Link.class, db.DatabaseProtos.Link.Builder.class);
    }

    private int bitField0_;
    public static final int MOVIEID_FIELD_NUMBER = 1;
    private int movieId_;
    /**
     * <code>required int32 movieId = 1;</code>
     */
    public boolean hasMovieId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 movieId = 1;</code>
     */
    public int getMovieId() {
      return movieId_;
    }

    public static final int IMDBID_FIELD_NUMBER = 2;
    private int imdbId_;
    /**
     * <code>required int32 imdbId = 2;</code>
     */
    public boolean hasImdbId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 imdbId = 2;</code>
     */
    public int getImdbId() {
      return imdbId_;
    }

    public static final int TMDBID_FIELD_NUMBER = 3;
    private int tmdbId_;
    /**
     * <code>required int32 tmdbId = 3;</code>
     */
    public boolean hasTmdbId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 tmdbId = 3;</code>
     */
    public int getTmdbId() {
      return tmdbId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMovieId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasImdbId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTmdbId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, movieId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, imdbId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, tmdbId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, movieId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, imdbId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, tmdbId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof db.DatabaseProtos.Link)) {
        return super.equals(obj);
      }
      db.DatabaseProtos.Link other = (db.DatabaseProtos.Link) obj;

      if (hasMovieId() != other.hasMovieId()) return false;
      if (hasMovieId()) {
        if (getMovieId()
            != other.getMovieId()) return false;
      }
      if (hasImdbId() != other.hasImdbId()) return false;
      if (hasImdbId()) {
        if (getImdbId()
            != other.getImdbId()) return false;
      }
      if (hasTmdbId() != other.hasTmdbId()) return false;
      if (hasTmdbId()) {
        if (getTmdbId()
            != other.getTmdbId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMovieId()) {
        hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
        hash = (53 * hash) + getMovieId();
      }
      if (hasImdbId()) {
        hash = (37 * hash) + IMDBID_FIELD_NUMBER;
        hash = (53 * hash) + getImdbId();
      }
      if (hasTmdbId()) {
        hash = (37 * hash) + TMDBID_FIELD_NUMBER;
        hash = (53 * hash) + getTmdbId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static db.DatabaseProtos.Link parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static db.DatabaseProtos.Link parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static db.DatabaseProtos.Link parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static db.DatabaseProtos.Link parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static db.DatabaseProtos.Link parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static db.DatabaseProtos.Link parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static db.DatabaseProtos.Link parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static db.DatabaseProtos.Link parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static db.DatabaseProtos.Link parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static db.DatabaseProtos.Link parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static db.DatabaseProtos.Link parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static db.DatabaseProtos.Link parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(db.DatabaseProtos.Link prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Link}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Link)
        db.DatabaseProtos.LinkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return db.DatabaseProtos.internal_static_protobuf_Link_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return db.DatabaseProtos.internal_static_protobuf_Link_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                db.DatabaseProtos.Link.class, db.DatabaseProtos.Link.Builder.class);
      }

      // Construct using db.DatabaseProtos.Link.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        movieId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        imdbId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        tmdbId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return db.DatabaseProtos.internal_static_protobuf_Link_descriptor;
      }

      @java.lang.Override
      public db.DatabaseProtos.Link getDefaultInstanceForType() {
        return db.DatabaseProtos.Link.getDefaultInstance();
      }

      @java.lang.Override
      public db.DatabaseProtos.Link build() {
        db.DatabaseProtos.Link result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public db.DatabaseProtos.Link buildPartial() {
        db.DatabaseProtos.Link result = new db.DatabaseProtos.Link(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.movieId_ = movieId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.imdbId_ = imdbId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.tmdbId_ = tmdbId_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof db.DatabaseProtos.Link) {
          return mergeFrom((db.DatabaseProtos.Link)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(db.DatabaseProtos.Link other) {
        if (other == db.DatabaseProtos.Link.getDefaultInstance()) return this;
        if (other.hasMovieId()) {
          setMovieId(other.getMovieId());
        }
        if (other.hasImdbId()) {
          setImdbId(other.getImdbId());
        }
        if (other.hasTmdbId()) {
          setTmdbId(other.getTmdbId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMovieId()) {
          return false;
        }
        if (!hasImdbId()) {
          return false;
        }
        if (!hasTmdbId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        db.DatabaseProtos.Link parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (db.DatabaseProtos.Link) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int movieId_ ;
      /**
       * <code>required int32 movieId = 1;</code>
       */
      public boolean hasMovieId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 movieId = 1;</code>
       */
      public int getMovieId() {
        return movieId_;
      }
      /**
       * <code>required int32 movieId = 1;</code>
       */
      public Builder setMovieId(int value) {
        bitField0_ |= 0x00000001;
        movieId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 movieId = 1;</code>
       */
      public Builder clearMovieId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        movieId_ = 0;
        onChanged();
        return this;
      }

      private int imdbId_ ;
      /**
       * <code>required int32 imdbId = 2;</code>
       */
      public boolean hasImdbId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 imdbId = 2;</code>
       */
      public int getImdbId() {
        return imdbId_;
      }
      /**
       * <code>required int32 imdbId = 2;</code>
       */
      public Builder setImdbId(int value) {
        bitField0_ |= 0x00000002;
        imdbId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 imdbId = 2;</code>
       */
      public Builder clearImdbId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        imdbId_ = 0;
        onChanged();
        return this;
      }

      private int tmdbId_ ;
      /**
       * <code>required int32 tmdbId = 3;</code>
       */
      public boolean hasTmdbId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 tmdbId = 3;</code>
       */
      public int getTmdbId() {
        return tmdbId_;
      }
      /**
       * <code>required int32 tmdbId = 3;</code>
       */
      public Builder setTmdbId(int value) {
        bitField0_ |= 0x00000004;
        tmdbId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 tmdbId = 3;</code>
       */
      public Builder clearTmdbId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tmdbId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Link)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Link)
    private static final db.DatabaseProtos.Link DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new db.DatabaseProtos.Link();
    }

    public static db.DatabaseProtos.Link getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Link>
        PARSER = new com.google.protobuf.AbstractParser<Link>() {
      @java.lang.Override
      public Link parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Link(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Link> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Link> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public db.DatabaseProtos.Link getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RatingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Rating)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 1;</code>
     */
    int getUserId();

    /**
     * <code>required int32 movieId = 2;</code>
     */
    boolean hasMovieId();
    /**
     * <code>required int32 movieId = 2;</code>
     */
    int getMovieId();

    /**
     * <code>required float rating = 3;</code>
     */
    boolean hasRating();
    /**
     * <code>required float rating = 3;</code>
     */
    float getRating();

    /**
     * <code>required int32 timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int32 timestamp = 4;</code>
     */
    int getTimestamp();
  }
  /**
   * Protobuf type {@code protobuf.Rating}
   */
  public  static final class Rating extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Rating)
      RatingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Rating.newBuilder() to construct.
    private Rating(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rating() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Rating(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              movieId_ = input.readInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              rating_ = input.readFloat();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return db.DatabaseProtos.internal_static_protobuf_Rating_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return db.DatabaseProtos.internal_static_protobuf_Rating_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              db.DatabaseProtos.Rating.class, db.DatabaseProtos.Rating.Builder.class);
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int MOVIEID_FIELD_NUMBER = 2;
    private int movieId_;
    /**
     * <code>required int32 movieId = 2;</code>
     */
    public boolean hasMovieId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 movieId = 2;</code>
     */
    public int getMovieId() {
      return movieId_;
    }

    public static final int RATING_FIELD_NUMBER = 3;
    private float rating_;
    /**
     * <code>required float rating = 3;</code>
     */
    public boolean hasRating() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required float rating = 3;</code>
     */
    public float getRating() {
      return rating_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private int timestamp_;
    /**
     * <code>required int32 timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 timestamp = 4;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMovieId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRating()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, movieId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(3, rating_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, movieId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, rating_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof db.DatabaseProtos.Rating)) {
        return super.equals(obj);
      }
      db.DatabaseProtos.Rating other = (db.DatabaseProtos.Rating) obj;

      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (getUserId()
            != other.getUserId()) return false;
      }
      if (hasMovieId() != other.hasMovieId()) return false;
      if (hasMovieId()) {
        if (getMovieId()
            != other.getMovieId()) return false;
      }
      if (hasRating() != other.hasRating()) return false;
      if (hasRating()) {
        if (java.lang.Float.floatToIntBits(getRating())
            != java.lang.Float.floatToIntBits(
                other.getRating())) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserId()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId();
      }
      if (hasMovieId()) {
        hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
        hash = (53 * hash) + getMovieId();
      }
      if (hasRating()) {
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRating());
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static db.DatabaseProtos.Rating parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static db.DatabaseProtos.Rating parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static db.DatabaseProtos.Rating parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static db.DatabaseProtos.Rating parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static db.DatabaseProtos.Rating parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static db.DatabaseProtos.Rating parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static db.DatabaseProtos.Rating parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static db.DatabaseProtos.Rating parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static db.DatabaseProtos.Rating parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static db.DatabaseProtos.Rating parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static db.DatabaseProtos.Rating parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static db.DatabaseProtos.Rating parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(db.DatabaseProtos.Rating prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Rating}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Rating)
        db.DatabaseProtos.RatingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return db.DatabaseProtos.internal_static_protobuf_Rating_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return db.DatabaseProtos.internal_static_protobuf_Rating_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                db.DatabaseProtos.Rating.class, db.DatabaseProtos.Rating.Builder.class);
      }

      // Construct using db.DatabaseProtos.Rating.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        movieId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        rating_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return db.DatabaseProtos.internal_static_protobuf_Rating_descriptor;
      }

      @java.lang.Override
      public db.DatabaseProtos.Rating getDefaultInstanceForType() {
        return db.DatabaseProtos.Rating.getDefaultInstance();
      }

      @java.lang.Override
      public db.DatabaseProtos.Rating build() {
        db.DatabaseProtos.Rating result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public db.DatabaseProtos.Rating buildPartial() {
        db.DatabaseProtos.Rating result = new db.DatabaseProtos.Rating(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.movieId_ = movieId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.rating_ = rating_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof db.DatabaseProtos.Rating) {
          return mergeFrom((db.DatabaseProtos.Rating)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(db.DatabaseProtos.Rating other) {
        if (other == db.DatabaseProtos.Rating.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasMovieId()) {
          setMovieId(other.getMovieId());
        }
        if (other.hasRating()) {
          setRating(other.getRating());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasUserId()) {
          return false;
        }
        if (!hasMovieId()) {
          return false;
        }
        if (!hasRating()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        db.DatabaseProtos.Rating parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (db.DatabaseProtos.Rating) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>required int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private int movieId_ ;
      /**
       * <code>required int32 movieId = 2;</code>
       */
      public boolean hasMovieId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 movieId = 2;</code>
       */
      public int getMovieId() {
        return movieId_;
      }
      /**
       * <code>required int32 movieId = 2;</code>
       */
      public Builder setMovieId(int value) {
        bitField0_ |= 0x00000002;
        movieId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 movieId = 2;</code>
       */
      public Builder clearMovieId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        movieId_ = 0;
        onChanged();
        return this;
      }

      private float rating_ ;
      /**
       * <code>required float rating = 3;</code>
       */
      public boolean hasRating() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required float rating = 3;</code>
       */
      public float getRating() {
        return rating_;
      }
      /**
       * <code>required float rating = 3;</code>
       */
      public Builder setRating(float value) {
        bitField0_ |= 0x00000004;
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float rating = 3;</code>
       */
      public Builder clearRating() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rating_ = 0F;
        onChanged();
        return this;
      }

      private int timestamp_ ;
      /**
       * <code>required int32 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 timestamp = 4;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int32 timestamp = 4;</code>
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Rating)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Rating)
    private static final db.DatabaseProtos.Rating DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new db.DatabaseProtos.Rating();
    }

    public static db.DatabaseProtos.Rating getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Rating>
        PARSER = new com.google.protobuf.AbstractParser<Rating>() {
      @java.lang.Override
      public Rating parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Rating(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Rating> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rating> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public db.DatabaseProtos.Rating getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Movie_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Movie_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Link_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Link_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Rating_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Rating_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016database.proto\022\010protobuf\"7\n\005Movie\022\017\n\007m" +
      "ovieId\030\001 \002(\005\022\r\n\005title\030\002 \002(\t\022\016\n\006genres\030\003 " +
      "\002(\t\"7\n\004Link\022\017\n\007movieId\030\001 \002(\005\022\016\n\006imdbId\030\002" +
      " \002(\005\022\016\n\006tmdbId\030\003 \002(\005\"L\n\006Rating\022\016\n\006userId" +
      "\030\001 \002(\005\022\017\n\007movieId\030\002 \002(\005\022\016\n\006rating\030\003 \002(\002\022" +
      "\021\n\ttimestamp\030\004 \002(\005B\024\n\002dbB\016DatabaseProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Movie_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Movie_descriptor,
        new java.lang.String[] { "MovieId", "Title", "Genres", });
    internal_static_protobuf_Link_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_Link_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Link_descriptor,
        new java.lang.String[] { "MovieId", "ImdbId", "TmdbId", });
    internal_static_protobuf_Rating_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protobuf_Rating_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Rating_descriptor,
        new java.lang.String[] { "UserId", "MovieId", "Rating", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
